sudo: false
language: php
php:
  - 7.3
  - 7.4
  - 8.0

before_script:
  - echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - phpenv config-rm xdebug.ini
  - phpenv rehash
  - composer install

cache:
  directories:
    - downloads
    - $HOME/.composer/cache
    - .php_cs.cache

script:
  - vendor/bin/phing ci-tasks
